In [1]:
import numpy as np
import pandas as pd

In [2]:
dogecoin = pd.read_csv("DOGE.csv")
dogecoin["symbol"] = "DOGE"
dogecoin["date"] = pd.to_datetime(dogecoin["date"])

vechain = pd.read_csv("VET.csv")
vechain["symbol"] = "VET"
vechain["date"] = pd.to_datetime(vechain["date"])

cardano = pd.read_csv("ADA.csv")
cardano["symbol"] = "ADA"
cardano["date"] = pd.to_datetime(cardano["date"])

hedera_hashgraph = pd.read_csv("HBAR.csv")
hedera_hashgraph["symbol"] = "HBAR"
hedera_hashgraph["date"] = pd.to_datetime(hedera_hashgraph["date"])

litecoin = pd.read_csv("LTC.csv")
litecoin["symbol"] = "LTC"
litecoin["date"] = pd.to_datetime(litecoin["date"])

stellar = pd.read_csv("XLM.csv")
stellar["symbol"] = "XLM"
stellar["date"] = pd.to_datetime(stellar["date"])

eos = pd.read_csv("EOS.csv")
eos["symbol"] = "EOS"
eos["date"] = pd.to_datetime(eos["date"])

tron = pd.read_csv("TRX.csv")
tron["symbol"] = "TRX"
tron["date"] = pd.to_datetime(tron["date"])

xrp = pd.read_csv("XRP.csv")
xrp["symbol"] = "XRP"
xrp["date"] = pd.to_datetime(xrp["date"])

tether = pd.read_csv("USDT.csv")
tether["symbol"] = "USDT"
tether["date"] = pd.to_datetime(tether["date"])

polkadot = pd.read_csv("DOT.csv")
polkadot["symbol"] = "DOT"
polkadot["date"] = pd.to_datetime(polkadot["date"])

solana = pd.read_csv("SOL.csv")
solana["symbol"] = "SOL"
solana["date"] = pd.to_datetime(solana["date"])

avalanche = pd.read_csv("AVAX.csv")
avalanche["symbol"] = "AVAX"
avalanche["date"] = pd.to_datetime(avalanche["date"])

theta = pd.read_csv("THETA.csv")
theta["symbol"] = "THETA"
theta["date"] = pd.to_datetime(theta["date"])

iota = pd.read_csv("MIOTA.csv")
iota["symbol"] = "MIOTA"
iota["date"] = pd.to_datetime(iota["date"])

uniswap = pd.read_csv("UNI.csv")
uniswap["symbol"] = "UNI"
uniswap["date"] = pd.to_datetime(uniswap["date"])

chainlink = pd.read_csv("LINK.csv")
chainlink["symbol"] = "LINK"
chainlink["date"] = pd.to_datetime(chainlink["date"])

monero = pd.read_csv("XMR.csv")
monero["symbol"] = "XMR"
monero["date"] = pd.to_datetime(monero["date"])

aave = pd.read_csv("AAVE.csv")
aave["symbol"] = "AAVE"
aave["date"] = pd.to_datetime(aave["date"])

maker = pd.read_csv("MKR.csv")
maker["symbol"] = "MKR"
maker["date"] = pd.to_datetime(maker["date"])

dash = pd.read_csv("DASH.csv")
dash["symbol"] = "DASH"
dash["date"] = pd.to_datetime(dash["date"])

In [3]:
combined_twitter = pd.concat([dogecoin, vechain, cardano, hedera_hashgraph, litecoin, stellar, eos, tron, xrp, tether, polkadot, solana, avalanche, theta, iota, uniswap, chainlink, monero, aave, maker, dash])
combined_twitter.drop(["Unnamed: 0"], axis=1, inplace=True)
combined_twitter = combined_twitter.sort_values(by = ["symbol", "date"])
combined_twitter

,date,num_tweets,replies_sum,retweets_sum,likes_sum,subjectivity_sum,polarity_sum,replies_avg,retweets_avg,likes_avg,subjectivity_avg,polarity_avg,tone_most_common,symbol
0,2021-01-01,175,356,269,2167,55.468704,12.221062,2.034286,1.537143,12.382857,0.316964,0.069835,Neutral,AAVE
1,2021-01-02,167,323,348,2826,52.802993,13.314617,1.934132,2.083832,16.922156,0.316186,0.079728,Positive,AAVE
2,2021-01-03,360,451,351,3992,96.812194,33.454420,1.252778,0.975000,11.088889,0.268923,0.092929,Neutral,AAVE
3,2021-01-04,438,453,325,3105,139.452321,55.558508,1.034247,0.742009,7.089041,0.318384,0.126846,Positive,AAVE
4,2021-01-05,443,426,380,3423,136.298156,42.986306,0.961625,0.857788,7.726862,0.307671,0.097035,Positive,AAVE
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
115,2021-04-26,4098,7236,16123,67855,1412.623629,494.148707,1.765739,3.934358,16.558077,0.344710,0.120583,Positive,XRP
116,2021-04-27,3337,7544,9598,60230,1182.201920,449.126825,2.260713,2.876236,18.049146,0.354271,0.134590,Positive,XRP
117,2021-04-28,2815,4358,7652,38325,1085.098407,364.984124,1.548135,2.718295,13.614565,0.385470,0.129657,Positive,XRP
118,2021-04-29,3667,9166,10199,70868,1222.025221,419.944414,2.499591,2.781293,19.325879,0.333249,0.114520,Neutral,XRP
119,2021-04-30,4227,8431,12901,75112,1396.095669,519.023679,1.994559,3.052046,17.769577,0.330280,0.122788,Positive,XRP

In [4]:
combined_twitter.to_csv('combined_twitter')